---
params:
  title: "On Creation of the R Markdown Thesis Template for DMS Students of MSU-IIT"
  author: "Rey R. Cuenca"
  program: "Bachelor of Science in Statistics"
  papertype: "Undergraduate Thesis"
  adviser: "Dr. Beloved N. Adviser"
  panelone: "Dr. Beloved N. Panel 1"
  paneltwo: "Dr. Beloved N. Panel 2"
  # panelthree: "Dr. Beloved N. Panel 3"
  # panelfour: "Dr. Beloved N. Panel 4"
  department: "Mathematics and Statistics"
  deptchair: "Dr. Beloved N. Chairperson"
  csmdean: "Dr. Beloved N. College-Dean"
  college: "College of Science and Mathematics"
  university: "Mindanao State University -- Iligan Institute of Technology"
  address: "Iligan City"
  sgsdean: "Dr. Beloved N. SGS-Dean"
  ddate: "August, 2022"
abstract: |
  `r paste(readLines("_abstract.Rmd"), collapse = "\n  ")`
site: bookdown::bookdown_site
documentclass: book
# logo: source/img/msuiit-logo.png # Uncomment this only after you finalize the ouput
bibliography: 
  - source/bib/book.bib
  - source/bib/packages.bib
description: |
  Undergraduate Thesis of Rey Cuenca
biblio-style: apalike
csl: source/bibstyle/apa-7th.csl
colorlinks: true
fontsize: 12pt
preview: true
---

```{r install_packages, include=FALSE}
source('source/r/install-missing-r-packages.R')
```

```{r child="_titlepage.Rmd"}
```

```{r child="_abstract.Rmd"}
```

```{r child="_dedication.Rmd"}
```

```{r child="_acknowledgment.Rmd"}
```

`\tableofcontents`{=latex}
`\addcontentsline{toc}{chapter}{TABLE OF CONTENTS}`{=latex}

`\newpage`{=latex}
`\pagenumbering{arabic}\setcounter{page}{1}`{=latex}

```{r child="_listofnotations.Rmd"}
```

`\listoffigures\newpage`{=latex}
`\addcontentsline{toc}{chapter}{LIST OF FIGURES}`{=latex}

`\listoftables\newpage`{=latex}
`\addcontentsline{toc}{chapter}{LIST OF TABLES}`{=latex}

